### ISSUE TITLE
Doesn't work on first opened buffer

### ISSUE THREAD

**Issue by lewis6991** [zsugabubus/crazy8.nvim#2]
I seem to need to run `edit!` in order for this to be triggered properly.

I added this to my init.lua as a workaround:

```lua
-- Hacky fix so it works on the first opened buffer
vim.cmd[[autocmd vimrc BufReadPost * autocmd CursorHold <buffer=abuf> ++once lua Crazy8()]]
```

**Comment by zsugabubus** [comment]
Are you sure it is not something with your setup? It works well for me:
```
nvim -u NORC --cmd 'packadd crazy8.nvim' file
```

**Comment by lewis6991** [comment]
Yes it is my setup. I have the file `dotfiles/nvim/after/ftplugin/lua.vim` which contains:

```viml
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
```

I have these files defined for numerous filetypes.

I presume these are being loaded after the crazy8 autocmds.

Maybe the best solution is for `lua.vim` to check if `setlocal` has already been set for these settings before running them.

**Comment by zsugabubus** [comment]
Is there any specific reason you use `after/ftplugin` instead of `ftplugin`? I guess `after/*` is there to override everything, so that is not really for defaults but to enforce some required settings.
